In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
import numpy as np

In [3]:
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
cols = list(pd.read_csv("C:\\Users\\Prasanna\\kaggle\\digit-recognizer\\train.csv", nrows =1))
x_train = pd.read_csv("C:\\Users\\Prasanna\\kaggle\\digit-recognizer\\train.csv", usecols =[i for i in cols if i != 'label'])
y_train = pd.read_csv("C:\\Users\\Prasanna\\kaggle\\digit-recognizer\\train.csv")['label']
x_test = pd.read_csv("C:\\Users\\Prasanna\\kaggle\\digit-recognizer\\test.csv", index_col=0)


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(512, activation='relu', input_shape=(784,)),
  tf.keras.layers.Dense(128),
  tf.keras.layers.Dense(128),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(np.array(x_train)).numpy()
predictions

array([[  29.363255,  -12.648758, -187.28905 , ...,  -88.84025 ,
          -5.754594, -119.17469 ],
       [ 107.86391 , -146.87169 , -319.90607 , ...,  -11.626019,
          59.622154, -212.6382  ],
       [  63.619923,   -7.780326, -116.62421 , ...,   90.384056,
          77.75776 ,  -83.01024 ],
       ...,
       [  89.807205,   57.2908  , -149.62923 , ...,  143.54506 ,
          12.121317,  -26.912508],
       [ 141.53745 ,  101.16283 , -224.09142 , ...,   95.680954,
         123.521965,   19.239328],
       [ -42.98989 ,   10.170087,  -45.129185, ...,   34.13719 ,
         -51.20533 ,   35.270756]], dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[2.4765464e-22, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.3879029e-37, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.3794857e-12, 0.0000000e+00, 0.0000000e+00, ..., 9.9999666e-01,
        3.2844864e-06, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 2.4357250e-28,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 2.9209623e-18, 0.0000000e+00, ..., 1.2155672e-20,
        1.4996035e-08, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train, predictions).numpy()

148.59654

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(np.array(x_train), np.array(y_train), epochs = 10)

Epoch 1/10
1313/1313 [==============================] - 5s 3ms/step - loss: 4.0105 - accuracy: 0.8616
Epoch 2/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.5956 - accuracy: 0.8969
Epoch 3/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.4807 - accuracy: 0.9075
Epoch 4/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.3895 - accuracy: 0.9207
Epoch 5/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.3209 - accuracy: 0.9327
Epoch 6/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.2887 - accuracy: 0.9367
Epoch 7/10
1313/1313 [==============================] - 5s 4ms/step - loss: 0.2137 - accuracy: 0.9497
Epoch 8/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.1989 - accuracy: 0.9530
Epoch 9/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1860 - accuracy: 0.9562
Epoch 10/10
1313/1313 [==============================] - 5s 4ms/step - loss: 0.193

In [12]:
ans = model.predict(x_test,  verbose='auto')

875/875 [==============================] - 2s 2ms/step


In [13]:
finals = np.zeros(28000)
for i in range(28000):
    finals[i] = np.argmax(ans[i])

In [14]:
finals

array([2., 0., 9., ..., 3., 9., 2.])

In [16]:
fileName = "Submission.csv"
df=pd.DataFrame(finals)
df.to_csv(fileName)